# Generated by Django 4.2.4 on 2023-08-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('score', models.IntegerField(max_length=3)),
                ('fairways', models.IntegerField(max_length=3)),
                ('putts', models.IntegerField(max_length=3)),
                ('greens', models.IntegerField(max_length=3)),
                ('pars', models.IntegerField(max_length=3)),
                ('birdies', models.IntegerField(max_length=3)),
                ('summary', models.TextField(max_length=2000)),
            ],
        ),
    ]
