# Generated by Django 4.2.4 on 2023-08-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birdies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fairways',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='greens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pars',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='putts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(),
        ),
    ]
